### ISSUE TITLE
消息计数

### ISSUE THREAD

**Issue by com028** [alberliu/gim#100]
假如：A用户分别收到了来自B、C用户的10条离线消息。A用户上线后，把这20条未读消息同步到客户端，只阅读了来自C的消息。此时服务器会把已阅读的seq标记为最大值（假设来自C的最大seq比来自B的大），那么A重新上线时，该如何显示来自B的10条未读消息？

**Comment by alberliu** [comment]
seq的最大值并不是已读的，是客户端收到的消息，客户端本地维护已读未读的消息计数
