### ISSUE TITLE
关于水平扩展

### ISSUE THREAD

**Issue by a775189488** [alberliu/gim#102]
看到你的框架结构。logic和conn都是可以水平扩展的吧，但是目前是否没有实现呢，因为对应的服务地址在config里面都是单一的。如果需要实现需要做哪些些事？

**Comment by alberliu** [comment]
最简单的做法，就是引入etcd等一些服务发现组件，然后把配置的IP改成从服务发现组件上面获取

**Comment by a775189488** [comment]
ok
