### ISSUE TITLE
测试websocket报错，请问如何处理？

### ISSUE THREAD

**Issue by stiffer831** [alberliu/gim#110]
![image](https://user-images.githubusercontent.com/23020938/132700912-7dfe6398-6113-43de-84a7-f14fddea6dbd.png)

**Comment by alberliu** [comment]
connect只能在linux下运行

**Comment by alberliu** [comment]
没看到截图，是不是升级了grpc的版本

**Comment by stiffer831** [comment]
您好，grpc如下  
![image](https://user-images.githubusercontent.com/23020938/132946904-74a60547-89ef-4b79-ac5f-311ee80849b2.png)

**Comment by stiffer831** [comment]
已可以正常运行，跑本地测试出现如下错误，请问如何处理呢，感谢！   
websocket: bad handshake
![Uploading image.png…]()

**Comment by stiffer831** [comment]
已可以正常运行，跑本地测试出现如下错误，请问如何处理呢，感谢！
websocket: bad handshake   
![image](https://user-images.githubusercontent.com/23020938/132953842-300bfb0e-9197-49ab-9362-e751439c1af9.png)

**Comment by stiffer831** [comment]
Fixed!
