### ISSUE TITLE
fim 长连接8080端口，出现连接又很快断开的情况

### ISSUE THREAD

**Issue by hongyouqin** [alberliu/gim#113]
fim长连接8080端口，等个几秒后看到服务器connect程序日志报“tcp读超时”，然后连接就断开了。请问作者出现这种情况的原因是什么。我只在internal/connect/tcp_server.go 的StartTCPServer里修改了超时时间gn.WithTimeout(5*time.Second, 10*time.Second)

**Comment by hongyouqin** [comment]
另外我发现始终有一个userid=0的在连接，本地数据库并没有userid=0的用户：

![image](https://user-images.githubusercontent.com/37205926/147050631-fc69016e-2b65-432a-a4b5-98c66dd537d4.png)

**Comment by alberliu** [comment]
1.看日志断开连接的原因是客户端发的包太大了，超过了能接收的最大容量
2.user_id ==0,是因为这个连接用户还没有登录，所以为0
