### ISSUE TITLE
如何把业务系统的账户信息传递给IM的USER表

### ISSUE THREAD

**Issue by duoyang2022** [alberliu/gim#114]
业务服务器只需要实现business.int.proto协议中定义的GRPC接口，为gim服务提供基本的用户功能即可.

请问如何理解这句话，我是用PHP作为客户端，什么时候把业务系统的用户信息传递给IM这边。
business.int.proto接口没有看到创建用户的方法
谢谢

**Comment by duoyang2022** [comment]
有点不好理解，能具体场景描述下吗？
是不是说，我的业务系统实现business.int，然后gim这边去调用。
目前gim是调用自己的business.ini，改成调用我这边业务系统实现的business.int

**Comment by alberliu** [comment]
这样做没问题

**Comment by duoyang2022** [comment]
我在尝试，改造gim项目的business部分，谢谢
