### ISSUE TITLE
Load config dynamically

### ISSUE THREAD

**Issue by 1Ckpwee** [alberliu/gim#118]
你好，这边我在学习该项目的时候有两个小疑惑：
- 是否需要为项目加载配置文件显式表明出来
- 其次我们可以使用 viper 动态为项目加载不同环境的配置文件
我近期会提交一个 PR 去做以上两件事情，与此同时也很感谢能开源这个项目🙏

**Comment by alberliu** [comment]
这个当时这样做是为了打包发布简单一点，直接生成一个二进制文件

**Comment by 1Ckpwee** [comment]
嗯我明白了。 这里我想如果用 docker 方式构建镜像可能会比较方便一些～ 我这边看下能否替换一下现有的打包方式。
