### ISSUE TITLE
config里的端口配置写错了 logic 和 business 的写反了 

### ISSUE THREAD

**Issue by TQCasey** [alberliu/gim#119]
config里的端口配置写错了 logic 和 business 的写反了

**Comment by alberliu** [comment]
我这边检查是没有问题的，可以提供详细一点信息

**Comment by TQCasey** [comment]
prod_conf.go 为例 

ConnectRPCAddr:  "addrs:///127.0.0.1:50000",
BusinessRPCAddr: "addrs:///127.0.0.1:50100",
LogicRPCAddr:    "addrs:///127.0.0.1:50200",

但是下面三个 
Connect 监听的 RPCListenAddr 是 50000
Logic 监听的 RPCListenAddr 是 50100 
Business 监听的 RPCListenAddr 是 50200  

其中 logic 和 business 的端口是反了的

**Comment by alberliu** [comment]
看到了，已经修复了，多谢提醒
