### ISSUE TITLE
是不是要出1.5.0的稳定版本了啊？

### ISSUE THREAD

**Issue by haijun568** [alberliu/gim#121]
看着好几个月没有更新了，是不是要出稳定版本了啊？
我们公司要做IM中台，给不同APP接入IM（单聊，群里，直播室聊天），看这个挺适合的。

还有这个gim有相关的压测报告吗？想看看性能咋样，能不能满足业务需求

**Comment by alberliu** [comment]
最近没有加入新功能的计划，暂时没有压测报告

**Comment by dkeepersun** [comment]
项目挺好的。要坚持维护更新。
