### ISSUE TITLE
你好，请问可以根据此项目改写成游戏对战服务器吗？

### ISSUE THREAD

**Issue by Kevin-free** [alberliu/gim#124]

**Comment by alberliu** [comment]
游戏对战类的对延迟要求比较高，TCP可能不合适

**Comment by Kevin-free** [comment]
麻烦大佬解释下为什么 TCP 可能不适合延迟要求高呢？那用什么比较合适呢？ （虽然我的游戏目前来看对延迟要求并不高：）




熊文涛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alberliu/gim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月5日(星期四) 下午4:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alberliu/gim] 你好，请问可以根据此项目改写成游戏对战服务器吗？ (Issue #124)





 
游戏对战类的对延迟要求比较高，TCP可能不合适

**Comment by feixintianxia** [comment]
定位不同。
这个项目可单独用于游戏或直播中IM聊天。
对于游戏的逻辑模块通信，可考虑skynet
