### ISSUE TITLE
codec的一些问题

### ISSUE THREAD

**Issue by slimValue** [alberliu/gim#135]
你好，问下 codec改用uvarint的方式，是出于修复什么问题？https://github.com/alberliu/gim/commit/ee5e7c9749e958a5128cea1287905a677878e45a

现在用 fim联调的时候，发现老版本codec是用 headLen的方式
https://github.com/alberliu/fim/blob/master/lib/net/socket_manager.dart

这边想问下 server不用headLen是因为有什么bug吗？

**Comment by zjywill** [comment]
能不能配合gim的修改 更新下fim的代码

**Comment by alberliu** [comment]
server的headLen没有什么bug, 只是uvarint更有优势，传输数据较小的时候，更节省流量，而且没有最大包限制，便于扩展。现在工作比较忙，没有精力维护fim了

**Comment by slimValue** [comment]
> server的headLen没有什么bug, 只是uvarint更有优势，传输数据较小的时候，更节省流量，而且没有最大包限制，便于扩展。现在工作比较忙，没有精力维护fim了

好的，感谢答复
