### ISSUE TITLE
测试包里面的client/tcp_client.go有一个地方报错

### ISSUE THREAD

**Issue by Stepkim** [alberliu/gim#21]
https://github.com/alberliu/gim/blob/81dbf0eadeef75bc221606d3bd75e4c4b53bbc9b/test/client/tcp_client.go#L47

原因是GetToken里面`expire`过期时间使用的是int64类型,而`time.Now().Add()`返回的是Time类型

**Comment by alberliu** [comment]
这个已经处理了
