### ISSUE TITLE
这个项目 之前不是叫goim吗 咋改成gim了？

### ISSUE THREAD

**Issue by wearetvxq** [alberliu/gim#23]

**Comment by wearetvxq** [comment]
之前是一个单纯的im服务器  可以创建用户并聊天，现在变成了一个可以于其他rpc应用对接的提供im服务的 服务了吗？

**Comment by alberliu** [comment]
因为和一个goim项目重名了，为了区分。
LogicClientExtServer和移动客户端对接，LogicServerExtServer和业务服务器对接，这样做，是为了让gim能能作为一个IM的中间平台
