### ISSUE TITLE
 之前关注的时候记得sendmessage 是在 connect层可以做的，现在是没有了吗？

### ISSUE THREAD

**Issue by wearetvxq** [alberliu/gim#24]
我不是很懂im 所以有几个地方不是很懂，可以的话，麻烦大概解答一下，或者分享一些文档，十分感谢。 我看的是没有grpc的情况（没学过grpc，所以先看没有grpc的版本了解逻辑），  现在看起来是 connect 暴露tcp端口50000，然后logic暴露8000端口主要是做用户注册创建组群等curd数据管理，然后http 还有一个sendmessage的接口，那么看起来 消息是由 service 这个模块来处理的  比起我之前看的版本  logic 处理http 业务  connect处理tcp长连接 发送消息。现在多了一个app 和service的改了有点蒙圈了，     那么引入 server 和app 是为了让启动 应用也能注册app 来使用im server的吗？  以及我能力有限 暂时只能先看一下 logic 处理 设备组群，connect来完成 消息收发的版本 该退回来那个git 提交。 按照之前的描述 应该是都可以用的吧，但是 service这块能否做一些更多的说明，十分感谢

**Comment by wearetvxq** [comment]
我找到了一些文档说明 可能我这个版本 把NSQ的异步通信关闭了？ 所以  我看到的只是 connect和logic rpc通信  signin 等简单的通信，消息相关的未找到？   能否给出 几个不同版本的问题git 版本

**Comment by wearetvxq** [comment]
90f9916f84994e8466b5b14e9d600120447ea94a  我是在这个分之。。。  Nov 9 10:56:24 2019 的 就是看了 加入grpc 之前的分之，然后这个分之里面的 mq 相关的全部注释掉了。。。 所以能否给一下 1 单纯的im服务器通信，2加入app service，3grpc等最新版本 这些不同阶段完善的版本大概日志， 一下子看最新的 有点吃力

**Comment by alberliu** [comment]
1.server 是用来对外对外提供接口的，grpc相比http的json的形式，性能高，接入方便。
2.app是用来区分业务的，比如公司可能有多个app都要接入
