### ISSUE TITLE
gim/logic/mq/consume/consumer.go有错误

### ISSUE THREAD

**Issue by Yukibana** [alberliu/gim#26]
这是我一个人的问题嘛，，首先是icmctx找不到，我看github上和本地的确实没有，然后是conf.NOQID没有转移到定义的那个结构体里面。

**Comment by alberliu** [comment]
你是什么时候拉的代码，imctx已经不用了，你拉一下最新的代码试试

**Comment by Yukibana** [comment]
我直接在github上看的代码也是这样的啊，就master分支，我也觉得很奇怪，编译通不过不可能传上来的
<img width="1136" alt="Screen Shot 2020-01-03 at 11 29 16" src="https://user-images.githubusercontent.com/39240496/71705845-4af8c200-2e1c-11ea-84a4-2081dffa97d1.png">

**Comment by alberliu** [comment]
你上传的图片我这边显示不出来，但是，项目我没有做任何改动，都是可以编译通过的

**Comment by alberliu** [comment]
图片看到了，这个文件现在已经用不到了

**Comment by Yukibana** [comment]
OK的
