### ISSUE TITLE
metadata 什么时候存的 app_id,user_id,device_id ？

### ISSUE THREAD

**Issue by jh235** [alberliu/gim#27]
我看到在 appId, userId, _, err := grpclib.GetCtxData(ctx)  [这从ctx 中取 appId, userId](https://github.com/alberliu/gim/blob/19b0ab69b0a6a592fb18a49584c83986a4aad5e1/api/logic/logic_client_ext.go#L40)   但是我没有找打往 metadata 里存 的代码

**Comment by alberliu** [comment]
func getCtx() context.Context {
	token, _ := util.GetToken(1, 2, 3, time.Now().Add(1*time.Hour).Unix(), util.PublicKey)
	return metadata.NewOutgoingContext(context.TODO(), metadata.Pairs(
		"app_id", "1",
		"user_id", "2",
		"device_id", "3",
		"token", token,
		"request_id", strconv.FormatInt(time.Now().UnixNano(), 10)))
}
你可以搜索一下这段代码，api都是服务对外提供的接口

**Comment by jh235** [comment]
@alberliu 你给的这代码都是test里的，其他文件里没有找到，但是在 项目里又需要去获取，所以有点疑惑

**Comment by alberliu** [comment]
其实你可以这样理解，这些数据就是客户端传上来的
