### ISSUE TITLE
减少sql对数据库版本的依赖

### ISSUE THREAD

**Issue by Xi0ng8** [alberliu/gim#28]
目前的sql中create_time,update_time在每个表都存在，message表还有个sendtime，由于使用了CURRENT_TIMESTAMP，低版本的mysql会报错，本来对于数据库版本没有什么依赖的，建议改掉，然后在dao里面使用 util.FormatTime(time.Now())处理。

低版本数据库还不支持utf8mb4，utf8mb4_bin，也可以一并改为utf8，utf8_unicode_ci，兼容性更好

**Comment by alberliu** [comment]
我还是推荐5.7以上的数据库

**Comment by harryboda** [comment]
我有数百台服务器在使用中，都用的5.5。而且这个timestamp的特性毫无意义，为了这个失去兼容性不值得。我自己都改掉了，你也可以继续不采用
