### ISSUE TITLE
IM 系统的几个问题解决了吗

### ISSUE THREAD

**Issue by JeffreyBool** [alberliu/gim#33]
- [ ] 消息一致性

- [ ] 消息可靠性

- [ ] 消息重试，超时等

- [ ] 离线消息投递

**Comment by alberliu** [comment]
消息可靠性，离线消息同步已经解决，你指的消息一致性，就是各端看到消息序列是一致吗，这个没有实现，至于消息重试，超时，说明连接不可用，要等到心跳超时做离线消息同步
