### ISSUE TITLE
请教消息时序问题

### ISSUE THREAD

**Issue by candivan** [alberliu/gim#35]
目前看代码 感觉是发送消息流程是同步的吗  就是A发送给B 需要B返回结果 A才能收到应答是吗

**Comment by alberliu** [comment]
对，目前消息没有做异步处理，A发送消息给B，首先，A发送消息给服务器，服务器将消息持久话，然后投递给B，此时就会给A应答消息发送成功，不需要等到B的ACK

**Comment by candivan** [comment]
这边发送消息对方是主动收到的吗，还是通过同步来处理的

**Comment by alberliu** [comment]
这得分情况，如果是离线消息，就要等到客户端长连接建立上来之后，主动同步，如果客户端在线，就通过TCP长连接直接下发了
