### ISSUE TITLE
服务水平扩展问题

### ISSUE THREAD

**Issue by Iceber** [alberliu/gim#36]
local  和 tcp_conn, ws_conn 点对点连接，在不依赖MQ的情况下如何做到服务水平扩展呢
无法准确发送到用户相应的长链接中

**Comment by alberliu** [comment]
redis里面保存了，设备建立的长连接和连接层机器的关系，如果多台连接层机器的话，可以用这个关系去找连接层机器

**Comment by tianye3017** [comment]
你好，是只有在配置了多台连接层机器时才会在redis里保存吗，我配置了一台连接层机器时在redis里没有找到这个关系。
