### ISSUE TITLE
想请问一下这个业务是什么意思

### ISSUE THREAD

**Issue by hitwell** [alberliu/gim#39]
logic层的cmd入口
	
// 初始化自增id配置
util.InitUID(db.DBCli)

代码大概看的懂，不太懂为啥这样做（业务逻辑吧），有相关话题文档么，

**Comment by hitwell** [comment]
好吧，我好像看懂了，
这个表示给指定的某业务做自增id
bus.._id   是指哪个业务
一条记录表示一个业务

是这样的吧，

**Comment by alberliu** [comment]
对，是这样的

**Comment by hitwell** [comment]
好的，谢谢。我上周开始学习写go，目前也有做一个im系统的任务，正在参考你的这个项目，多谢不吝赐教

**Comment by alberliu** [comment]
可以多多交流
