### ISSUE TITLE
请问一下,他这个能做分布式吗?需要接入其他微服务的框架吗? 比如使用一个etcd来做 服务注册和服务发现

### ISSUE THREAD

**Issue by wearetvxq** [alberliu/gim#40]
conn 和logic 的grpc 连接都是写的对方的端口嘛,是否  在grpc连接处 写一个类似zk或者etcd 的地址,然后调用时 再从etcd里面拿到 当前可用的对方在线服务呢?

**Comment by alberliu** [comment]
现在还不支持服务发现，不过我写了一个pkg/grpclib/addrs_resolver.go，可以支持多个IP的负载均衡，类似于这样，rpc_cli.InitLogicIntClient("addrs:///127.0.0.1:50000,127.0.0.1:50001")
