### ISSUE TITLE
业务服务器接入的话 还是需要用手机客户端的 rpc接口来做 用户注册和组群管理吗?

### ISSUE THREAD

**Issue by wearetvxq** [alberliu/gim#42]
![image](https://user-images.githubusercontent.com/32411303/78251621-32d03600-7524-11ea-85c0-d2177e0cafaf.png)

**Comment by wearetvxq** [comment]
所以 业务服务器 只是能用im里面的用户体系,来主动给im的一些用户来发送消息?  我记得之前的版本 业务服务器 好像有也 自己的 创建用户等一系列api的

**Comment by alberliu** [comment]
1.业务服务器接入的话 还是需要用手机客户端的 rpc接口来做 用户注册和组群管理吗？
是的，用户注册和组群管理也可以让业务服务器去做，只不过这部分代码还没有实现
2.所以 业务服务器 只是能用im里面的用户体系？
业务服务器也需要有自己的用户体系，只不过需要做业务服务器和IM服务器的用户数据同步
