### ISSUE TITLE
关于几个返回

### ISSUE THREAD

**Issue by hitwell** [alberliu/gim#44]
internal/logic/service/app.go
![微信截图_20200406112122](https://user-images.githubusercontent.com/3361954/78520319-c3469900-77f8-11ea-9b32-d125df755630.png)

这个app的serveice 为什么Get方法中调用的方法报错，还返回nil

但是其他的文件，如 internal/logic/service/user.go，报错则service返回了错误
![微信截图_20200406112303](https://user-images.githubusercontent.com/3361954/78520409-043ead80-77f9-11ea-867c-56c4de0229fd.png)

**Comment by hitwell** [comment]
我贴了图片，你能看到么，我自己好像看不到我的贴图，

**Comment by hitwell** [comment]
我之前提了一个issue，也是这个疑问，因为当时，我只看了这一个service/app.go
总感觉怪怪的，但是说不出哪里有疑问，后来被我关闭了那个issue

我现在看到了第二个service，看了相似的逻辑，才发现，的确在相似的逻辑中，有不同的这个错误返回值。
如果service/app.go的Get方法，返回错误，不用处理的话，返回nil也无所谓，但是，我看调用该方法的时候，也错了错误的处理。

所以，我感觉怪怪的，

**Comment by alberliu** [comment]
对，这儿写的确实有问题，我已经改了，谢谢提醒
