### ISSUE TITLE
请教关于丢消息的问题

### ISSUE THREAD

**Issue by tangtaoit** [alberliu/gim#46]
非常感谢作者提供的优秀开源作品
我有如下疑问想请教下：
1.如果建立im连接后同步消息，在同步消息之前收到了消息A 客户端最新的序列号将是A这条的序列号，如果去同步消息，A消息之前的消息将会丢失。
2. 如果同步消息后再建立im连接，在同步消息完成和建立im连接成功之前的时间内有人发送消息这消息将会丢失。

**Comment by alberliu** [comment]
1.关于这个,客户端应该做一个限制，建立连接后，尚未同步消息之前，收到的消息，先暂时保存，不更新本地最大同步序列号。
2.同步消息一定是建立IM连接之后，消息同步是使用TCP长连接去做的
