### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by hitwell** [alberliu/gim#48]
你好，问一下，
![image](https://user-images.githubusercontent.com/3361954/80330342-801b9b00-8877-11ea-8bf2-ccc5e630cd27.png)
为啥这个地方要一个for循环呀，

**Comment by alberliu** [comment]
是为了不断的接收客户端发上来的数据

**Comment by hitwell** [comment]
> 是为了不断的接收客户端发上来的数据

因为我试了一下，不用for，也能接收到数据，是有一定的时效吗？

还有，我看到很多人在go的协程里面，写一个for死循环，这种写法，

**Comment by hitwell** [comment]
这个ws的DoConn 方法，没有使用协程go，返回去看下，

还有 判断 数据进来时候 appId == 0 || userId == 0 || deviceId == 0 || token == ""
![image](https://user-images.githubusercontent.com/3361954/80479527-b5acab00-8981-11ea-85dd-4d2d88cfae19.png)
为空的情况下，没有写return

**Comment by pydr** [comment]
> > 是为了不断的接收客户端发上来的数据
> 
> 
> 
> 因为我试了一下，不用for，也能接收到数据，是有一定的时效吗？
> 
> 
> 
> 还有，我看到很多人在go的协程里面，写一个for死循环，这种写法，

for 循环一直从 conn 中取数据，当没有数据时 ReadMessage() 会阻塞，当 conn Close 的时候， ReadMessage() 会返回 err.

**Comment by hitwell** [comment]
想问下，
![image](https://user-images.githubusercontent.com/3361954/80553662-41175200-89fd-11ea-81a2-2398daac9df1.png)
为什么这个用PreConn=-1，不再写一个方法直接断掉之前的连接（设备业务端不下线），
如果用PreConn=-1，那么sync.Map的manager里面，是不是有很多=-1的连接呀，

**Comment by hitwell** [comment]
![image](https://user-images.githubusercontent.com/3361954/80557267-f4397880-8a08-11ea-882d-a39e42ef6347.png)
这个地方，release之后，应该return一下吧，

**Comment by hitwell** [comment]
![image](https://user-images.githubusercontent.com/3361954/80559796-51d1c300-8a11-11ea-8c59-fe250ed608d2.png)
再问下，这个在web/h5端，也是可以调用rpc协议的么，

**Comment by hitwell** [comment]
> > > 是为了不断的接收客户端发上来的数据
> > 
> > 
> > 因为我试了一下，不用for，也能接收到数据，是有一定的时效吗？
> > 还有，我看到很多人在go的协程里面，写一个for死循环，这种写法，
> 
> for 循环一直从 conn 中取数据，当没有数据时 ReadMessage() 会阻塞，当 conn Close 的时候， ReadMessage() 会返回 err.

好的，谢谢

**Comment by alberliu** [comment]
js是可以调用grpc的服务的

**Comment by alberliu** [comment]
那个地方确实应该return，已经处理了，谢谢提醒
