### ISSUE TITLE
关于im

### ISSUE THREAD

**Issue by hitwell** [alberliu/gim#49]
再请教一个业务和设计上的问题，我这边需要做一个电商客服系统。
如果我要加一个“好友/联系人”的功能，我是在其他业务系统里面做这个关系业务逻辑和存储，还是说在这个IM系统里面做呢？
我想，如果在这个IM系统里面写，感觉怪怪的，
因为没整过im即时通讯类的业务，也没用过rpc，所以希望指点一下，

**Comment by alberliu** [comment]
gim的职责是抽离IM相关的业务功能，当时我认为，好友关系应该由业务方去维护，而不是IM，所以gim就没有实现好友相关功能，我建议还是在业务系统里面做。
