### ISSUE TITLE
关于Codec与NewCodecFactory找不到的问题

### ISSUE THREAD

**Issue by SAIKAII** [alberliu/gim#52]
alberliu你好，我发现bench/tcp_conn/main.go中的Codec类型与NewCodecFactory函数找不到，请问是什么原因？

**Comment by alberliu** [comment]
你可以更新一下代码，这个问题已经改过了。

**Comment by SAIKAII** [comment]
> 你可以更新一下代码，这个问题已经改过了。

更新过了，还是没有。tcp_conn包中没有相应的类型与函数。

**Comment by alberliu** [comment]
确定一下，你那边有更新到
`func (c *TcpClient) Start() {
	connect, err := net.Dial("tcp", "localhost:8080")
	if err != nil {
		fmt.Println(err)
		return
	}

	c.codec = util2.NewCodec(connect)

	c.SignIn()
	c.SyncTrigger()
	go c.Heartbeat()
	go c.Receive()
}`
最新的代码应该是这样的

**Comment by SAIKAII** [comment]
我这边看到的是
`func (c *TcpClient) Start() {
	connect, err := net.Dial("tcp", "localhost:8080")
	if err != nil {
		fmt.Println(err)
		return
	}

	c.codec = codecFactory.GetCodec(connect)

	c.SignIn()
	c.SyncTrigger()
	go c.Heartbeat()
}`
你master里的也是上面那样。是否你修改了代码但忘记更新了呢？

**Comment by alberliu** [comment]
我刚刚检查的是github上面的master代码，你可以看一下，可以确定提交了

**Comment by SAIKAII** [comment]
我上面贴的代码就是master里的，我这边看到bench/tcp_conn/main.go最后一次提交是4个月前。

**Comment by alberliu** [comment]
你不要看你本地的，你在github上面看
![image](https://user-images.githubusercontent.com/24761362/80918928-ffd6c780-8d99-11ea-8ddf-792079d9b8eb.png)

**Comment by SAIKAII** [comment]
哦，原来我们说的不是同一个目录的，我一直说的是bench目录下的，不过问题不大，我去照着test下的改就好了。
