### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by hitwell** [alberliu/gim#54]
关于 
![image](https://user-images.githubusercontent.com/3361954/81246907-528ada80-904b-11ea-9d88-f19600214bb3.png)
这个 Command 和 Custom 这两类消息，能举个例子么，

**Comment by alberliu** [comment]
custom当初是为了业务服务器的消息扩展，不过，Custom完全可以用Command替代，这要看实际的业务了

**Comment by hitwell** [comment]
再问下，
![image](https://user-images.githubusercontent.com/3361954/81365578-18890980-911b-11ea-9b13-71858bf64367.png)
这里，先jsoniter marshal，然后将bytes转string
我看jsoniter 有个函数 marshaltostring ，这个函数和 util.Bytes2str，效果是一样的吧，差别在哪里么，性能么，

**Comment by hitwell** [comment]
我觉得这个问题，有点那啥，我自己再看看吧，

**Comment by alberliu** [comment]
marshaltostring这个方法，我没有用过，原生的string（bytes）会有一次内存拷贝，util.Bytes2str不会进行内存拷贝

**Comment by alberliu** [comment]
刚刚看了MarshalToString的实现，底层用的也是 string(stream.Buffer())，所以util.Bytes2str性能会好一点
