### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by hitwell** [alberliu/gim#55]
![image](https://user-images.githubusercontent.com/3361954/81539846-6021c680-93a3-11ea-868b-4c223667f0f1.png)

![image](https://user-images.githubusercontent.com/3361954/81539991-952e1900-93a3-11ea-8e17-b43e3250672c.png)

为什么deviceId 要这种方式来获取，而不是用数据库的自增id呢，
是考虑性能，还是其他原因，我看这边用了个协程在跑，

**Comment by alberliu** [comment]
不用自增主键，其实最大的考虑就是以后好做分库分表

**Comment by hitwell** [comment]
好的，我之前想到过这点。现在又一下没找到原因。
以为是因为用到了协程，就需要这么写法，
如果做分库分表的话，有没有必要把 device_id 的字段类型变化下呢，现在是int，是否uuid一类的合适呢，

**Comment by alberliu** [comment]
bigint占用的空间更小
