### ISSUE TITLE
websocket请求时不能带header头

### ISSUE THREAD

**Issue by dkeepersun** [alberliu/gim#59]
因为客户端建立websocket链接时不能带header头。  貌似没有好办法在请求时加上user_id,token这些信息，
鉴权有没有其他更好的方案？

**Comment by dkeepersun** [comment]
![image](https://user-images.githubusercontent.com/2715388/82899474-a1ae9600-9f8d-11ea-9dfc-a465294cdd1b.png)

**Comment by qq475281441** [comment]
不带heade里可以带在请求参数后，比如  websocket://xxx.com?a=1&b=2

**Comment by alberliu** [comment]
这个有很多人反馈，已经改了
