### ISSUE TITLE
请检查是否少了return

### ISSUE THREAD

**Issue by dkeepersun** [alberliu/gim#60]
![image](https://user-images.githubusercontent.com/2715388/82930457-07177c80-9fb8-11ea-9448-c4639f4f744a.png)

**Comment by dkeepersun** [comment]
还有 在sql种 message 表的app_id字段应该是bigint吧

程序写的挺简洁的。学习中

**Comment by alberliu** [comment]
你提的两个问题，我都已经修复了，谢谢提醒
