### ISSUE TITLE
SQL statement error

### ISSUE THREAD

**Issue by ZuoFuhong** [alberliu/gim#61]
![image](https://user-images.githubusercontent.com/19775205/83091714-6a93ce00-a0ce-11ea-9b84-92cac13b2247.png)

**Comment by ZuoFuhong** [comment]
已提交pr

**Comment by dkeepersun** [comment]
![image](https://user-images.githubusercontent.com/2715388/83166549-aae06400-a141-11ea-9c74-17751eb4120d.png)


源代码里面，少了个一个?  sql会报错

**Comment by alberliu** [comment]
“少了个一个?”，这个错误已经修复，你的pr已经merge，谢谢你的提醒
