### ISSUE TITLE
关于deviceId的疑问 

### ISSUE THREAD

**Issue by Sunsongoing** [alberliu/gim#66]
我想用账号密码登录，登录时如何获取deviceId？每次登录都注册一次设备吗？

**Comment by alberliu** [comment]
就是APP下载后，本地没有device_id的时候，一个设备只需要注册一次，以后都不用在注册了

**Comment by Sunsongoing** [comment]
> 就是APP下载后，本地没有device_id的时候，一个设备只需要注册一次，以后都不用在注册了

但是本地的device_id如果被清理了，用户不就相当于凭空多出一个设备吗？

**Comment by alberliu** [comment]
这个关系不大，重新注册一下就可以

**Comment by Sunsongoing** [comment]
> 这个关系不大，重新注册一下就可以可以

ok
