### ISSUE TITLE
昨天更新之后，在哪里添加用户到IM服务器啊

### ISSUE THREAD

**Issue by Sunsongoing** [alberliu/gim#67]

**Comment by alberliu** [comment]
这次版本是一个大的更新，和以前完全不一样了，当前版本有独立的user服务，如果你是想尝试接入自己的业务服务器，可以替换掉user服务，但是你的业务服务器需要实现user.int.proto下面的协议

**Comment by Sunsongoing** [comment]
能大致说一下这次更新之后的设备注册和用户添加流程吗

**Comment by Sunsongoing** [comment]
出一个文档吧，大佬

**Comment by Wiidz** [comment]
同求出个文档，摸不着头脑
