### ISSUE TITLE
测试用例无法跑起来

### ISSUE THREAD

**Issue by cashwar3** [alberliu/gim#69]
cmd/ws_conn 目录下执行 go run main.go
test/ws_conn  目录下执行 go run main.go，有报错：dial error websocket: bad handshake 

调试发现服务端无法获取UserId、DeviceId、RequestId和token 的值

**Comment by phbai** [comment]
把ws_conn/main.go 32行
`conn, resp, err := websocket.DefaultDialer.Dial(path, http.Header{})`
里面的path写死就行了
`conn, resp, err := websocket.DefaultDialer.Dial("ws://localhost:8081/ws?user_id=1&device_id=1&token=0", http.Header{})`

**Comment by alberliu** [comment]
这个我已经改了，可能是你本地代码太旧了，更新一下看看
