### ISSUE TITLE
目前的ack机制会对db造成压力

### ISSUE THREAD

**Issue by liangjfblue** [alberliu/gim#70]
每条消息都rpc到logic ack, 然后更新db的设别表的ack, 网关层并发多大, 就有多大并发透传到logic的db了

**Comment by alberliu** [comment]
这个确实在并发量比较高的情况下，数据库的压力会比较大，所以就单独抽出来了，以后方便做优化

**Comment by botsphp** [comment]
ACK 和连接句柄，最好扔到 Cache 中，然后定时落表。现在表的压力过大。

**Comment by alberliu** [comment]
是的，这是一个不错的建议，以后这块会优化的

**Comment by 29395373** [comment]
可能用clickhouse数据库能更快一些

**Comment by alberliu** [comment]
ack已经改为写入到Redis
