### ISSUE TITLE
Vue跑不起来

### ISSUE THREAD

**Issue by leekoo3** [alberliu/gim#72]
VueWebSocket.getInstance().send(singleMsgReq).then(res => {
        //发送成功后消息会回调回来，接下来入库啊，显示什么的可以在这里处理
        console.log(res);
        })

singleMsgReq这个不知道具体是什么格式的对象

MsgHandler.js中
const MessageTitle = window.messageTitle.messageTitle
这个MessageTitle像魔法一样出现的 也不清楚是具体什么格式

import Snowflake from '@/utils/Snowflake'
这个文件不存在

**Comment by alberliu** [comment]
WebSocket这一块应该应该很稳定的，之前有人接入过完整的流程，我对前端不是很熟悉

**Comment by leekoo3** [comment]
String[] descriptorData = {
        "\n\rMessage.proto\"\222\001\n\007Message\022\n\n\002id\030\001 \001(\t\022" +
                "\020\n\010serverId\030\002 \001(\t\022\017\n\007reqType\030\003 \001(\005\022\017\n\007ms" +
                "gTime\030\004 \001(\003\022\013\n\003ack\030\005 \001(\t\022\016\n\006fromId\030\006 \001(\t" +
                "\022\014\n\004toId\030\007 \001(\t\022\014\n\004body\030\010 \001(\t\022\016\n\006status\030\t" +
                " \001(\005B\016B\014MessageClassb\006proto3"
};这段代码是不是写死的不能修改  我添加额外的2个字段能加进去吗17.09.2020, 11:12, "Alber" <notifications@github.com>:
WebSocket这一块应该应该很稳定的，之前有人接入过完整的流程，我对前端不是很熟悉
