### ISSUE TITLE
RegisterDevice报错

### ISSUE THREAD

**Issue by phbai** [alberliu/gim#74]
调用LogicExt.RegisterDevice报错提示`Error 1146: Table 'gim.device_ack' doesn't exist`

![image](https://user-images.githubusercontent.com/10389270/96569719-0f23e000-12fc-11eb-959f-079a17503a38.png)
应该是ACK改成写入redis之后 还有部分代码使用到device_ack这张表

**Comment by alberliu** [comment]
是的，有一部分代码没有去掉，现在已经去掉了，谢谢提醒
