### ISSUE TITLE
关于test/test_conn中登录用户后，不能实时接收消息的问题

### ISSUE THREAD

**Issue by Damon-yuan** [alberliu/gim#76]
您好，目前我按照文档用logic_ext_test.go里的TestLogicExtServer_SendMessage函数给模拟的user发消息，同时登录了test/test_conn的用户，发现登录的user只能读取到之前的所有消息，心跳响应和receive函数一直在运行着，却读不到最新的消息。请问这是怎么回事呢？期待您的解答～

**Comment by Damon-yuan** [comment]
test_conn/main.go 里最后的case pb.PackageType_PT_MESSAGE好像一直都走不到这个分支，好像把对方发的消息都当成离线消息啦

**Comment by alberliu** [comment]
你可以提供一些截图信息，看下是怎们填参的

**Comment by Damon-yuan** [comment]
好的，目前是这样的，我先用test/test_conn登录，userID, deviceID, sequence分别为1 1 0，设备id已经注册过了。客户端便进入了监听状态。

然后用TestLogicExtServer_SendMessage函数给在线设备发了消息，消息content为“test”，然后写在代码里的参数是sender userid为1，设备为2，也注册过。

最后结果就是客户端一直在监听状态，只能接收到heartbeat消息，收不到实时的消息。只有退出再登录才能以接收离线消息的方式拉到之前那条“test”消息。

**Comment by Damon-yuan** [comment]
现在问题已经定位到了 internal/tcp_conn/deliver_message.go 里的DeliverMessage函数，
`func DeliverMessage(ctx context.Context, req *pb.DeliverMessageReq) error {
	// 获取设备对应的TCP连接
	// fmt.Println("server: %+v", *server)
	conn, ok := server.GetConn(int(req.Fd))
	if !ok {
		logger.Logger.Warn("GetConn warn", zap.Int64("device_id", req.DeviceId), zap.Int64("df", req.Fd))
		return nil
	}
	fmt.Println("----------------------------------111111")

	data := conn.GetData().(ConnData)
	if data.DeviceId != req.DeviceId {
		logger.Logger.Warn("GetConn warn", zap.Int64("device_id", req.DeviceId), zap.Int64("df", req.Fd))
		return nil
	}
	fmt.Println("----------------------------------222222")
	Handler.Send(conn, pb.PackageType_PT_MESSAGE, grpclib.GetCtxRequstId(ctx), nil, req.Message)
	return nil
}`

server.GetConn(int(req.Fd))这个会执行失败，我打印了一下server，能输出server结构体的conns syn.map类型,长这样：{{map[11:0xc0000119e0 12:0xc00040e118] false}} map[] 0} ，req.Fd=11和12也是对的，但是GetConn(int(req.Fd)却读不到map里的内容。。

**Comment by Damon-yuan** [comment]
麻烦您抽空看一眼，十分感谢～

**Comment by alberliu** [comment]
这个问题已经修复了，当时更新网络库gn的时候，改出的一个bug，因为获取连接的时候，key的类型不一致导致的，谢谢你的反馈

**Comment by Damon-yuan** [comment]
好滴！！我去试试，respect！！

**Comment by Damon-yuan** [comment]
成功了，谢谢作者。respect！
