### ISSUE TITLE
【bug】GetUserGroups无法返回群组的avatarUrl

### ISSUE THREAD

**Issue by phbai** [alberliu/gim#80]
![image](https://user-images.githubusercontent.com/10389270/99630667-44dff400-2a75-11eb-96b1-5802360f7834.png)
https://github.com/alberliu/gim/blob/master/internal/logic/api/logic_ext.go#L163

**Comment by alberliu** [comment]
这个稍微晚会会补上的

**Comment by alberliu** [comment]
已经修复
