### ISSUE TITLE
注册登录只能通过RPC来实现吗

### ISSUE THREAD

**Issue by crystal-lee** [alberliu/gim#81]
1.调用LogicExt.RegisterDevice接口，完成设备注册，获取设备ID（device_id）
2.调用UserExt.SignIn接口，完成账户登录，获取账户登录的token。  
步骤1和2只能通过RPC来实现吗？

**Comment by alberliu** [comment]
是的，只能用GRPC调用

**Comment by crystal-lee** [comment]
好的，计划提供http的接口吗？
如果VUE要接入的话，现在是不是只能用grpc-web，在代理层做rpc的处理？还是有什么更好的方案呢？

**Comment by alberliu** [comment]
暂时不计划提供http,前端也可以使用grpc来介入，是的只能使用grpc-web

**Comment by crystal-lee** [comment]
好的，不行我就自己包个http,或者用grpc-web了
