### ISSUE TITLE
[功能请求] 添加频道

### ISSUE THREAD

**Issue by ilovesusu** [alberliu/gim#84]
是否考虑添加类似于TG频道的功能

**Comment by alberliu** [comment]
其实大群组聊天和频道的功能是类似的，目前gim支持大群组聊天

**Comment by ilovesusu** [comment]
https://telegram.org/tour/channels

电报频道可以有无限数量的订阅者，只有管理员有权发布信息。

是有点类似  但是大群组就需要禁言了

**Comment by alberliu** [comment]
这种订阅，目前不在计划中
