### ISSUE TITLE
代码有问题，找不到方式

### ISSUE THREAD

**Issue by xinjiayu** [alberliu/gim#86]
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/microrain/gowork #gosetup
/usr/local/go/bin/go build -o /private/var/folders/ww/wbxyqv115bq_7f6n8fr6h_pr0000gn/T/___go_build_gim_cmd_tcp_conn gim/cmd/tcp_conn #gosetup
# github.com/alberliu/gn
../../../../gowork/pkg/mod/github.com/alberliu/gn@v1.5.1/server.go:137:18: undefined: epoll
../../../../gowork/pkg/mod/github.com/alberliu/gn@v1.5.1/server.go:161:16: undefined: EpollCreate

**Comment by alberliu** [comment]
这个是没问题的，tcp_conn只有在Linux下可以执行

**Comment by yfly-github** [comment]
在mac下也有同样的问题呢
