### ISSUE TITLE
客户端如何接入，也是用grpc吗？

### ISSUE THREAD

**Issue by jh235** [alberliu/gim#88]
app客户端如何接入，也是用grpc吗？grpc主要是服务端使用，客户端支持不是太好

**Comment by alberliu** [comment]
是的，app接入也是grpc，我这边更倾向于grpc，如果不喜欢grpc的形式，可以使用grpc-gateway做一个中转

**Comment by jh235** [comment]
我尝试过grpc-gateway，没搞定，作者使用过 grpc-gateway吗？

**Comment by alberliu** [comment]
我这边也没用过

**Comment by smil4ever** [comment]
@alberliu 研究了很久grpc接口的接入方式，入门使用门槛较高，js的grpc根本就无法支持，强烈建议实现ws或tcp的协议或http的接口支持！

**Comment by alberliu** [comment]
解决web端的grpc接入，有两种方式
一种是服务端处理，使用 grpc-gateway提供http+json的接口
第二种是客户端使用grpc接入，可以使用https://github.com/grpc/grpc-web，之前和一个前端对接过，我们使用这个接入成功
后续我这边可以考虑grpc和http+json两种接口形式都提供
