### ISSUE TITLE
读代码后，才发现设计不尽人意。

### ISSUE THREAD

**Issue by baixiaoshi** [alberliu/gim#90]
1、接入不友好，发送消息接口在logic里面，而且是grpc协议的，对web是不友好的。建议聊天相关接口用长连接，用户好友操作接口用http足够。
2、nsq队列没有接入，目前还是比较简陋的。
3、代码接口命名不规范，文件命名不规范。logic_int 中的int是什么。

后来者如果想要im功能，推荐goim或者自己写一个简单的，比读gim代码花费时间少。

**Comment by alberliu** [comment]
1.我们项目中就是在使用grpc,相比使用http+json,我们不需要维护接口文档，协议即文档；可以生成客户端代码，客户端访问服务器，就像访问本地方法一样。
2.nsq之前版本中是用到的，后来为了简化设计，就移除了，如果服务器压力不大的话，就没有接入的必要。
3.ext是对外提供的接口，提供给客户端使用的，int是内部接口，服务内部之间调用的用的。

**Comment by alberliu** [comment]
talk is cheap，show me your code
