### ISSUE TITLE
将proto文件生成c++文件后无法通过编译

### ISSUE THREAD

**Issue by FlyWM** [alberliu/gim#91]
protobuf 版本3.14，grpc 1.33，c++11/14/17，vs2019，会报一堆错误。库文件什么的都链接正常，请问我还需要注意哪些问题。

**Comment by alberliu** [comment]
我这边编译go 和dart都没问题，对于c++不是很熟悉

**Comment by FlyWM** [comment]
> 我这边编译go 和dart都没问题，对于c++不是很熟悉

解决了，文件编码的问题，之前有个警告没注意到/(ㄒoㄒ)/~~
