### ISSUE TITLE
浏览器如何发送消息

### ISSUE THREAD

**Issue by svier** [alberliu/gim#94]
我看到 websocket 服务端只有处理同步消息 心跳 和消息回执，发送消息获取好友列表等其它操作都没有实现，是本来就打算那部分使用 grpc 接口还是打算后面会实现

**Comment by svier** [comment]
折腾了半个多月才理顺完全跑通
我目前由于是后台系统使用，所以是先在网站上有登录状态才开始加载 IM 模块，所以这边是先通过 ajax 接口使用 php 调用 grpc 获取 token 然后前端使用 websocket 接入 
如果wsserver 不打算实现其它操作的话 那就只能继续通过 ajax 接口间接用 php 去调用 grpc 感觉很麻烦呀

**Comment by alberliu** [comment]
js可以直接调用grpc接口的，使用起来也很方便

**Comment by svier** [comment]
就是说 wsserver 只能接收消息 发消息只能用 grpc 了

**Comment by alberliu** [comment]
是的

**Comment by svier** [comment]
这使用门槛也太高了 连接了一个 ws 不够用 还得要走grpc
